### ISSUE TITLE
Membersページにおける職名｢助教授｣を｢助教｣に修正

### ISSUE THREAD

**Issue by Nansurezo** [HPCSLab/web#31]
Membersのページにおいて、藤田先生・小林先生・多田野先生の職名が｢助教授｣になっていますが、｢助教｣が正しいかと思います。
細かいことかもしれませんが、助教授は現在の准教授に相当する古い呼び方で、助教とは明確に別なので、区別した方が良い気がします。

参考 (文科省より)
https://www.mext.go.jp/b_menu/shingi/chukyo/chukyo4/houkoku/attach/1342439.htm

**Comment by namachan10777** [comment]
ご指摘ありがとうございます 🙏  修正します

**Comment by namachan10777** [comment]
マージしたのでIssueをcloseします。デプロイは#33 のマージ後に #33 と一緒に行います。
