### ISSUE TITLE
卒研配属ページで名前のリンクが404 Not foundになる

### ISSUE THREAD

**Issue by shuuji3** [HPCSLab/web#36]
リンク先が `/members/tatebe` などになっているので、ページが存在しませんでした。

例: https://www.hpcs.cs.tsukuba.ac.jp/bachelor#:~:text=%E5%8B%9F%E9%9B%86%E4%BA%BA%E6%95%B0-,%E5%BB%BA%E9%83%A8%20%E4%BF%AE%E8%A6%8B,-3%20%E4%BA%BA

**Comment by shuuji3** [comment]
https://github.com/tsukuba-hpcs/hpcs-web/blob/479ba70672b7af9ec0ee14c7ed0aaea706207dec/src/components/pages/bachelor/TeamCard.astro#L44

**Comment by namachan10777** [comment]
直しました

**Comment by shuuji3** [comment]
ありがとうございます！
