### ISSUE TITLE
カルーセルの自動スライドでHA-PACSがスキップされる

### ISSUE THREAD

**Issue by shuuji3** [HPCSLab/web#37]
HA-PACSの1つ手前のHA-PACS/TCAまで来ると、1枚目のPegasusに戻ってしまいます。

**Comment by namachan10777** [comment]
これ私の環境だと再現しませんでした。ブラウザ等の情報をいただきたいです

**Comment by shuuji3** [comment]
改めてテストしてみたところ、Linux (Pop_OS!) のGoogle Chromeでだけ発生する問題だとわかりました (Firefoxや、macOSのGoogle Chrome、Firefoxでは問題なし)。

おそらくこの環境でだけ右側に幅のあるスライダーが常時表示されるので、幅の計算がずれているのだと思います。

![Screenshot from 2024-03-29 12-16-30](https://github.com/HPCSLab/web/assets/1425259/a1b06535-6c2f-4ae1-97bf-e71c1995e3da)

**Comment by shuuji3** [comment]
幅の計算で `window.innerWidth` が使われているのが原因かもしれません。

https://github.com/tsukuba-hpcs/hpcs-web/blob/479ba70672b7af9ec0ee14c7ed0aaea706207dec/src/components/display/Carousel.astro#L135

> The read-only Window property innerWidth returns the interior width of the window in pixels (that is, the width of the window's layout viewport). That includes the width of the vertical scroll bar, if one is present.

https://developer.mozilla.org/en-US/docs/Web/API/Window/innerWidth

**Comment by shuuji3** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Element/clientWidth

**Comment by namachan10777** [comment]
なるほど、ありがとうございます 🙇  下記Issueと合わせて修正します

* https://github.com/HPCSLab/web/issues/41

**Comment by shuuji3** [comment]
@namachan10777 すみません、いまコメントを見ました。`scroll()`ではなく、画像の幅が`100vw`の場合にスクロールバー分(15px)だけ幅が広くなっていることが原因だったので、`100%`にすると問題が起こらなくなりました。もし別の方法があればcloseしても構いません。

**Comment by shuuji3** [comment]
ref. New CSS Viewport Units Do Not Solve The Classic Scrollbar Problem — Smashing Magazine - https://www.smashingmagazine.com/2023/12/new-css-viewport-units-not-solve-classic-scrollbar-problem/
