### ISSUE TITLE
ESLintをFlatConfigへ移行する

### ISSUE THREAD

**Issue by namachan10777** [HPCSLab/web#67]
`typescript-eslint`、`@eslint/js`などは移行可能であることを確認済み。ESLint v8までは既存のプラグインもおそらく`@eslint/eslintrc`の`FlatCompat`で移行できる。ただしv9 + `FlatCompat`では以降出来ないプラグインもあるようなので、確認が必要。

# 関連

- https://github.com/HPCSLab/web/pull/55
- https://github.com/HPCSLab/web/pull/54

**Comment by shuuji3** [comment]
fixed by #138
